name:   shell commands
on: [workflow_dispatch] 
jobs:
  run-shell-commands:
    runs-on:  ubuntu-latest
    steps:
      - 
        name: "Print message"
        run:  echo "Hello Abhishek this is custom workflow so pls run it manually"  
      - 
        name: multiline script
        run:  |
          node -v
          npm -v
          python --version
      - 
        name: run and use python shell
        run:  |
          import platform
          print(platform.processor())
        shell: python
  run-powershell-commands:
    runs-on:  windows-latest
    steps:
      - 
        name: Print pwd
        run:  get-location
        shell: powershell
      - 
        name: print computername
        run:  $env:COMPUTERNAME
        shell: powershell




