name:   shell commands
on: [workflow_dispatch] 
jobs:
  run-shell-commands:
    runs-on:    ubuntu-latest
    steps:
      - 
        name: "Print message"
        run:  echo "Hello Abhishek this is custom workflow so pls run it manually"  
      - 
        name:   multiline script
        run:    |
            node -v
            npm -v
            python --version
    


